# Perceptron Implementation

In [ ]:
!pip install joblib

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import os
import matplotlib.pyplot as plt
import joblib   #it is used to save as binary
import numpy as np
import pandas as pd

In [ ]:
# eta is learning rate. 1e-4 = 10 to the power of -4. this can be ignored. but by using this type. it saves time. and give smaller values. 
class Percep:
  def __init__(self, eta: float=None, epochs: int=None):
    self.weights = np.random.randn(3) * 1e-4
    self.eta = eta   #it is learning rate
    self.epochs = epochs #this is nothing but max iterations

  def _z_outcome(self, inputs, weights):
    return np.dot(inputs, weights)

  def activation_function(self, z):
    return np.where(z > 0, 1, 0)

  #defining fit method. 
  def fit(self, x, y):
    self.x = x
    self.y = y

    X_with_bias = np.c_[self.x, -np.ones((len(self.x), 1))]
    print(f"X with bias: \n{X_with_bias}")

    for epoch in range(self.epochs):
      print("--"*10)
      print(f"for epoch >> {epoch + 1}")
      print("--"*10)

      z= self._z_outcome(X_with_bias, self.weights)
      y_hat = self.activation_function(z)
      print(f"predicted value after forward pass: \n{y_hat}")

      self.error = self.y - y_hat
      print(f"error: \n{self.error}")
            
      self.weights = self.weights + self.eta * np.dot(X_with_bias.T, self.error)
      print(f"updated weights after epoch: {epoch + 1}/{self.epochs}: \n{self.weights}")
      print(f"##"*10)
            
            
  def predict(self, X):
        X_with_bias = np.c_[X, -np.ones((len(X), 1))]
        z = self._z_outcome(X_with_bias, self.weights)
        return self.activation_function(z)
    


In [ ]:
OR = {
    "x1": [0,0,1,1],
    "x2": [0,1,0,1],
    "y" : [0,1,1,1]
}

df_OR = pd.DataFrame(OR)

df_OR

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  1

In [ ]:
def prepare_data(df, target_col="y"):
    X = df.drop(target_col, axis=1)
    y = df[target_col]
    
    return X, y

In [ ]:
X, y = prepare_data(df_OR)
X

x1  x2
0   0   0
1   0   1
2   1   0
3   1   1

perceptron will only work on linear data. and fails in non - linear data

In [ ]:
X, y = prepare_data(df_OR)

ETA = 0.1
EPOCHS = 10

model_or = Percep(eta=ETA, epochs=EPOCHS)

model_or.fit(X, y)

X with bias: 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
--------------------
for epoch >> 1
--------------------
predicted value after forward pass: 
[0 0 0 0]
error: 
0    0
1    1
2    1
3    1
Name: y, dtype: int64
updated weights after epoch: 1/10: 
[ 0.19996081  0.19998443 -0.29999882]
####################
--------------------
for epoch >> 2
--------------------
predicted value after forward pass: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after epoch: 2/10: 
[ 0.19996081  0.19998443 -0.19999882]
####################
--------------------
for epoch >> 3
--------------------
predicted value after forward pass: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after epoch: 3/10: 
[ 0.19996081  0.19998443 -0.09999882]
####################
--------------------
for epoch >> 4
--------------------
predicted value after forward pass: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3    0
Name: y, dtype

In [ ]:
-np.ones((6, 1))  #here its nothing but creating metrix like 2*3 ,  3*3..

In [ ]:
#ANN - Artificial neural networks.